### PR TITLE
Correct Hibernate Warnings

### LINKED ISSUE #201: [BUG] Hibernate WARN 88050
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table img_post_comments drop constraint FKbf4rwnww2l9fd40lmv8ldjncv" via JDBC Statement
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table img_post_comments drop constraint FKthyfg59t3wh9xeisnxklim0pt" via JDBC Statement
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table img_posts drop constraint FK8msfabssmy1qyrgbw6nxhuhty" via JDBC Statement
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table img_posts_img_post_comments drop constraint FK8y7l9x07vyer7ifp5m1ap73vx" via JDBC Statement
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table img_posts_img_post_comments drop constraint FK2u4rvcbojxddbsx2jcm219gj2" via JDBC Statement
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table users drop constraint FK94vcs3jm4btpclnlp7mt6u87t" via JDBC Statement
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table users drop constraint FKqjp6iwe2anthe5yx88fl0coan" via JDBC Statement
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table users drop constraint FKptl8qqltogy0q1xywjbf842ly" via JDBC Statement
- [x] Error executing DDL "alter table img_post_comments add constraint FKbf4rwnww2l9fd40lmv8ldjncv foreign key (author_id) references users" via JDBC Statement
- [x] GenerationTarget encountered exception accepting command : Error executing DDL "alter table img_posts add constraint FK8msfabssmy1qyrgbw6nxhuhty foreign key (author_id) references users" via JDBC Statement

### PR DESCRIPTION
**Pull request by FullSol**

### CODE REVIEW

File: src/main/java/com/amplifier/repositories/ImgPostCommentRepository.java [hunk 1]
```diff
@@ -11,21 +11,21 @@
...
     @Query(value = "SELECT * FROM img_post_comments WHERE author_id = ?1", nativeQuery = true)
-    public Comment findByAuthorId(int authorId);
+    public ImgPostComment findByAuthorId(int authorId);
 
     @Query(value = "SELECT * FROM img_post_comments WHERE img_post_id = ?1", nativeQuery = true)
-    public Comment findImagePostId(int imgPostId);
+    public ImgPostComment findImagePostId(int imgPostId);
 
-    @Query(value = "UPDATE img_post_comments SET comment_text, comment_text = ?1", nativeQuery= true)
+    @Query(value = "UPDATE img_post_comments SET comment_text, comment_text = ?1", nativeQuery = true)
```
Comment (L3viathon) [inline src/main/java/com/amplifier/repositories/ImgPostCommentRepository.java]: Shouldn't this be
`@Query(value = "UPDATE img_post_comments SET comment_text = ?1 WHERE id = ?2", nativeQuery = true)` ?

**Review by L3viathon — APPROVED** [review]

**Comment by FullSol** [comment]
Yes. You are correct.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
