### PR TITLE
[BUG] Create UserSocialMediaIntTest

### LINKED ISSUE #138: [BUG] SocialMediaService Test

### PR DESCRIPTION
**Pull request by FullSol**
- Created all required tests
- Noted steps involved
- Cleaned up dependencies

### CODE REVIEW

File: src/test/java/com/amplifier/services/UserSocialMediaIntTest.java [hunk 1]
```diff
@@ -0,0 +1,136 @@
+package com.amplifier.services;
```
Comment (FullSol) [inline src/test/java/com/amplifier/services/UserSocialMediaIntTest.java:1]: This file was just moved and whitespace removed

File: src/test/java/com/amplifier/services/CharacterServiceTests.java [hunk 2]
```diff
@@ -0,0 +1,170 @@
+package com.amplifier.services;
```
Comment (FullSol) [inline src/test/java/com/amplifier/services/CharacterServiceTests.java:1]: This file was just moved and whitespace removed

**Review by L3viathon — APPROVED** [review]
Gr8~~~
