### PR TITLE
Boot Bug Zapping

### LINKED ISSUE #123: [BUG] Springboot Boot Up

### PR DESCRIPTION
**Pull request by FullSol**
Correcting issued being thrown by SpringBoot in an attempt to boot.

### CODE REVIEW

File: src/main/java/com/amplifier/controllers/CommentController.java [hunk 1]
```diff
@@ -33,29 +33,29 @@
...
     @ApiOperation(value = "Create new comment entity", notes = "Adding a new comment through the API")
-    public @ResponseBody ClientMessage add(@RequestBody Comment comment) {
+    public @ResponseBody ClientMessage add(@RequestBody ImgPostComment comment) {
         return service.add(comment) ? CREATION_SUCCESSFUL : CREATION_FAILED;
     }
 
     @PatchMapping("/comment")
     @ApiOperation(value = "Update comment entity", notes = "Editing a comment through the API")
-    public @ResponseBody ClientMessage edi(@RequestBody Comment comment) {
+    public @ResponseBody ClientMessage edi(@RequestBody ImgPostComment comment) {
```
Comment (L3viathon) [inline src/main/java/com/amplifier/controllers/CommentController.java:58]: Did you want to call this method "edi"?

**Review by L3viathon — APPROVED** [review]
Thank you for all that you've done Mister Calvin~

File: src/main/java/com/amplifier/controllers/CommentController.java (hunk 1 above)
Comment (FullSol) [reply src/main/java/com/amplifier/controllers/CommentController.java:58]: Nope, should be edit.
